$ANSIBLE_VAULT;1.1;AES256
63316439646432326566306538333264333830373431373765616234323836633333646161653566
3663333335346231666431353863396561393732633930360a623866393533393232353665373233
66333439613264373335663330353733383936373132646139643334376432653935613737373431
3864633335613332390a366535333739376537623137653561386663613432326239343438356233
30613133393333333066393634313331383235353333333931396237663633346231643265616639
3263373063616636383638376238363563366638613933613334