    - name: "nginx setup for {{ component }}"
      ansible.builtin.import_role:
        name: common
        tasks_from: nginx_setup.yaml

    - name: Removing default content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
      
    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: delete {{ component }} zip file
      ansible.builtin.file:
        path: /tmp/{{ component }}.zip
        state: absent

    - name: Download {{ component }} code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
        dest: /tmp/{{ component }}.zip      

    - name: Extract {{ component }}.zip  into /usr/share/nginx/html
      ansible.builtin.unarchive:
        src: /tmp/{{ component }}.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: remove default nginx
      ansible.builtin.file:
        state: absent
        path: /etc/nginx/nginx.conf

    - name: copy nginx.conf file to /etc/nginx/nginx.conf
      throttle: 2
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
