    - name: Installing mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

# service start and enable
    - name: start mysql server
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes 

    - name: setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1