    - name: disable redis module
      ansible.builtin.command: dnf module disable redis -y

    - name: enable redis module 7
      ansible.builtin.command: dnf module enable redis:7 -y

    - name: Install redis
      ansible.builtin.dnf:
        name: redis
        state: present