    - name: copy service file to /etc/systemd/system/{{ component }}.service
      ansible.builtin.template:
        src: "{{ component }}.service.j2"
        dest: /etc/systemd/system/{{ component }}.service
      notify: start {{ component }}
      
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true